USE
    sample101;
DROP TABLE IF EXISTS
    users;
CREATE TABLE IF NOT EXISTS users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD CHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);